spring:
  application:
    name: foodtech

  datasource:
    url: jdbc:h2:mem:projectfoodtech
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console